FROM oven/bun:1.3.1 AS base

ARG PUBLIC_AACSEARCH_ENDPOINT
ENV PUBLIC_AACSEARCH_ENDPOINT ${PUBLIC_AACSEARCH_ENDPOINT}

ARG PUBLIC_AACSEARCH_DASHBOARD
ENV PUBLIC_AACSEARCH_DASHBOARD ${PUBLIC_AACSEARCH_DASHBOARD}

ARG PUBLIC_AACSEARCH_COL_MESSAGES_ID
ENV PUBLIC_AACSEARCH_COL_MESSAGES_ID ${PUBLIC_AACSEARCH_COL_MESSAGES_ID}

ARG PUBLIC_AACSEARCH_COL_THREADS_ID
ENV PUBLIC_AACSEARCH_COL_THREADS_ID ${PUBLIC_AACSEARCH_COL_THREADS_ID}

ARG PUBLIC_AACSEARCH_DB_MAIN_ID
ENV PUBLIC_AACSEARCH_DB_MAIN_ID ${PUBLIC_AACSEARCH_DB_MAIN_ID}

ARG PUBLIC_AACSEARCH_FN_TLDR_ID
ENV PUBLIC_AACSEARCH_FN_TLDR_ID ${PUBLIC_AACSEARCH_FN_TLDR_ID}

ARG PUBLIC_AACSEARCH_PROJECT_ID
ENV PUBLIC_AACSEARCH_PROJECT_ID ${PUBLIC_AACSEARCH_PROJECT_ID}

ARG PUBLIC_AACSEARCH_PROJECT_INIT_ID
ENV PUBLIC_AACSEARCH_PROJECT_INIT_ID ${PUBLIC_AACSEARCH_PROJECT_INIT_ID}

ARG PUBLIC_GROWTH_ENDPOINT
ENV PUBLIC_GROWTH_ENDPOINT ${PUBLIC_GROWTH_ENDPOINT}

ARG PUBLIC_POSTHOG_API_KEY
ENV PUBLIC_POSTHOG_API_KEY ${PUBLIC_POSTHOG_API_KEY}

ARG AACSEARCH_DB_INIT_ID
ENV AACSEARCH_DB_INIT_ID ${AACSEARCH_DB_INIT_ID}

ARG AACSEARCH_COL_INIT_ID
ENV AACSEARCH_COL_INIT_ID ${AACSEARCH_COL_INIT_ID}

ARG AACSEARCH_API_KEY_INIT
ENV AACSEARCH_API_KEY_INIT ${AACSEARCH_API_KEY_INIT}

ARG GITHUB_TOKEN
ENV GITHUB_TOKEN ${GITHUB_TOKEN}

ARG SENTRY_AUTH_TOKEN
ENV SENTRY_AUTH_TOKEN ${SENTRY_AUTH_TOKEN}

ARG SENTRY_RELEASE
ENV SENTRY_RELEASE ${SENTRY_RELEASE}

ARG PUBLIC_POSTHOG_API_KEY
ENV PUBLIC_POSTHOG_API_KEY ${PUBLIC_POSTHOG_API_KEY}

WORKDIR /app
COPY package.json package.json
COPY bun.lock bun.lock

FROM base AS build

RUN bun install --frozen-lockfile
COPY . .
RUN bun run sync
RUN bun run build

FROM base AS prod-deps

RUN bun install --frozen-lockfile --production

FROM node:22-bullseye AS final

# Install fontconfig
COPY ./local-fonts /usr/share/fonts
RUN apt-get update && \
	apt-get install -y fontconfig && \
	apt-get autoremove --purge && \
	rm -rf /var/lib/apt/lists/*
RUN fc-cache -f -v

COPY --from=build /app/build/ build
COPY --from=build /app/server/ server
COPY --from=prod-deps /app/node_modules/ node_modules

CMD ["node", "server/main.js"]
